# -*- coding: utf-8 -*-
"""problem1_find_maximum.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aG28TP0brKAoBrcJRvAOvmGDTiAwXT0z
"""

import sys

input = sys.stdin.read
data = input().split()

index = 0
T = int(data[index])
index += 1

for _ in range(T):
    n = int(data[index])
    index += 1
    arr = [int(data[index + i]) for i in range(n)]
    index += n

    # Day 2 logic: Find Maximum
    maximum = max(arr)
    print(maximum)