# -*- coding: utf-8 -*-
"""Day1_Problem1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YTiLH14AKrgIoxKuqoV3t_F8o6uiefLX
"""

import sys

test_input = """2
4
1 3 5 7
3
10 20 30
"""

#simulate input
import sys
sys.stdin = open('test_input.txt', 'w')
sys.stdin.write(test_input)
sys.stdin = open('test_input.txt', 'r')

def main():
  input = sys.stdin.read
  data = input().split()

  index = 0
  T = int(data[index])
  index += 1

  for _ in range(T):
    n = int(data[index])
    index += 1
    arr = [int(data[index + i]) for i in range(n)]
    index += n
    print(sum(arr))

if __name__ == "__main__":
  sample = "2\n4\n1 3 5 7\n3\n10 20 30"
  sys.stdin = open('text_input.txt', 'w')
  sys.stdin.write(sample)
  sys.stdin.close()

  sys.stdin = open ('test_input.txt', 'r')
  main()